development:
  adapter: postgresql
  encoding: utf8
  database: screenfo_api_development
  username: karlpotenciano
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: screenfo_api_development
  username: karlpotenciano
  password:
  host: localhost

staging:
  adapter: postgresql
  encoding: utf8
  database: school_insider_stag
  host: localhost

production:
  url: ENV['DATABASE_URL']
