# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93f5dada911c762a9ddff9c6c08a07492912e9ed1b7671b2ce7b36f268d4a197cd886503aaca18069aad67822f6e3ef28ca079c3adaecf1cf6e67145a98b0852

test:
  secret_key_base: 53c072419ca1a05c21cc7549d142085acf92d36105c57fc75ca3f88ab11fcab077ec59646263bc3900b5e17bc0f0f8075bfe3ad6b1df8fa0fbca16e372819cce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
